-- currency
TRUNCATE TABLE `currency`;
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (1,'Afghanistan','Afghanistan Afghani', 'AFN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (2,'Albania','Albanian Lek','ALL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (3,'Algeria','Algerian Dinar','DZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (4,'American Samoa','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (5,'Andorra','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (6,'Angola','Angolan Kwanza','AOA');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (7,'Anguilla','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (8,'Antarctica','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (9,'Antigua and Barbuda','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (10,'Argentina','Argentine Peso','ARS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (11,'Armenia','Armenian Dram','AMD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (12,'Aruba','Aruban Guilder','AWG');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (13,'Australia','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (14,'Austria','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (15,'Azerbaijan','Azerbaijan New Manat','AZN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (16,'Bahamas','Bahamian Dollar','BSD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (17,'Bahrain','Bahraini Dinar','BHD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (18,'Bangladesh','Bangladeshi Taka','BDT');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (19,'Barbados','Barbados Dollar','BBD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (20,'Belarus','Belarussian Ruble','BYR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (21,'Belgium','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (22,'Belize','Belize Dollar','BZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (23,'Benin','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (24,'Bermuda','Bermudian Dollar','BMD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (25,'Bhutan','Bhutan Ngultrum','BTN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (26,'Bolivia','Boliviano','BOB');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (27,'Bosnia-Herzegovina','Marka','BAM');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (28,'Botswana','Botswana Pula','BWP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (29,'Bouvet Island','Norwegian Krone','NOK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (30,'Brazil','Brazilian Real','BRL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (31,'British Indian Ocean Territory','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (32,'Brunei Darussalam','Brunei Dollar','BND');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (33,'Bulgaria','Bulgarian Lev','BGN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (34,'Burkina Faso','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (35,'Burundi','Burundi Franc','BIF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (36,'Cambodia','Kampuchean Riel','KHR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (37,'Cameroon','CFA Franc BEAC','XAF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (38,'Canada','Canadian Dollar','CAD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (39,'Cape Verde','Cape Verde Escudo','CVE');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (40,'Cayman Islands','Cayman Islands Dollar','KYD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (41,'Central African Republic','CFA Franc BEAC','XAF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (42,'Chad','CFA Franc BEAC','XAF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (43,'Chile','Chilean Peso','CLP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (44,'China','Yuan Renminbi','CNY');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (45,'Christmas Island','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (46,'Cocos (Keeling) Islands','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (47,'Colombia','Colombian Peso','COP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (48,'Comoros','Comoros Franc','KMF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (49,'Congo',',CFA Franc BEAC','XAF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (50,'Congo, Dem. Republic','Francs','CDF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (51,'Cook Islands','New Zealand Dollar','NZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (52,'Costa Rica','Costa Rican Colon','CRC');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (53,'Croatia','Croatian Kuna','HRK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (54,'Cuba','Cuban Peso','CUP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (55,'Cyprus','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (56,'Czech Rep.','Czech Koruna','CZK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (57,'Denmark','Danish Krone','DKK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (58,'Djibouti','Djibouti Franc','DJF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (59,'Dominica','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (60,'Dominican Republic','Dominican Peso','DOP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (61,'Ecuador','Ecuador Sucre','ECS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (62,'Egypt','Egyptian Pound','EGP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (63,'El Salvador','El Salvador Colon','SVC');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (64,'Equatorial Guinea','CFA Franc BEAC','XAF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (65,'Eritrea','Eritrean Nakfa','ERN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (66,'Estonia','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (67,'Ethiopia','Ethiopian Birr','ETB');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (68,'European Union','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (69,'Falkland Islands (Malvinas)','Falkland Islands Pound','FKP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (70,'Faroe Islands','Danish Krone','DKK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (71,'Fiji','Fiji Dollar','FJD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (72,'Finland','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (73,'France','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (74,'French Guiana','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (75,'French Southern Territories','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (76,'Gabon','CFA Franc BEAC','XAF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (77,'Gambia','Gambian Dalasi','GMD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (78,'Georgia','Georgian Lari','GEL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (79,'Germany','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (80,'Ghana','Ghanaian Cedi','GHS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (81,'Gibraltar','Gibraltar Pound','GIP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (82,'Great Britain','Pound Sterling','GBP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (83,'Greece','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (84,'Greenland','Danish Krone','DKK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (85,'Grenada','East Carribean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (86,'Guadeloupe (French)','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (87,'Guam (USA)','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (88,'Guatemala','Guatemalan Quetzal','QTQ');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (89,'Guernsey','Pound Sterling','GGP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (90,'Guinea','Guinea Franc','GNF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (91,'Guinea Bissau','Guinea-Bissau Peso','GWP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (92,'Guyana','Guyana Dollar','GYD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (93,'Haiti','Haitian Gourde','HTG');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (94,'Heard Island and McDonald Islands','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (95,'Honduras','Honduran Lempira','HNL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (96,'Hong Kong','Hong Kong Dollar','HKD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (97,'Hungary','Hungarian Forint','HUF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (98,'Iceland','Iceland Krona','ISK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (99,'India','Indian Rupee','INR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (100,'Indonesia','Indonesian Rupiah','IDR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (101,'Iran','Iranian Rial','IRR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (102,'Iraq','Iraqi Dinar','IQD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (103,'Ireland','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (104,'Isle of Man','Pound Sterling','GBP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (105,'Israel','Israeli New Shekel','ILS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (106,'Italy','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (107,'Ivory Coast','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (108,'Jamaica','Jamaican Dollar','JMD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (109,'Japan','Japanese Yen','JPY');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (110,'Jersey','Pound Sterling','GBP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (111,'Jordan','Jordanian Dinar','JOD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (112,'Kazakhstan','Kazakhstan Tenge','KZT');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (113,'Kenya','Kenyan Shilling','KES');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (114,'Kiribati','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (115,'Korea-North','North Korean Won','KPW');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (116,'Korea-South','Korean Won','KRW');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (117,'Kuwait','Kuwaiti Dinar','KWD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (118,'Kyrgyzstan','Som','KGS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (119,'Laos','Lao Kip','LAK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (120,'Latvia','Latvian Lats','LVL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (121,'Lebanon','Lebanese Pound','LBP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (122,'Lesotho','Lesotho Loti','LSL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (123,'Liberia','Liberian Dollar','LRD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (124,'Libya','Libyan Dinar','LYD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (125,'Liechtenstein','Swiss Franc','CHF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (126,'Lithuania','Lithuanian Litas','LTL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (127,'Luxembourg','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (128,'Macau','Macau Pataca','MOP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (129,'Macedonia','Denar','MKD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (130,'Madagascar','Malagasy Franc','MGF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (131,'Malawi','Malawi Kwacha','MWK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (132,'Malaysia','Malaysian Ringgit','MYR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (133,'Maldives','Maldive Rufiyaa','MVR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (134,'Mali','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (135,'Malta','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (136,'Marshall Islands','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (137,'Martinique (French)','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (138,'Mauritania','Mauritanian Ouguiya','MRO');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (139,'Mauritius','Mauritius Rupee','MUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (140,'Mayotte','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (141,'Mexico','Mexican Nuevo Peso','MXN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (142,'Micronesia','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (143,'Moldova','Moldovan Leu','MDL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (144,'Monaco','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (145,'Mongolia','Mongolian Tugrik','MNT');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (146,'Montenegro','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (147,'Montserrat','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (148,'Morocco','Moroccan Dirham','MAD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (149,'Mozambique','Mozambique Metical','MZN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (150,'Myanmar','Myanmar Kyat','MMK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (151,'Namibia','Namibian Dollar','NAD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (152,'Nauru','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (153,'Nepal','Nepalese Rupee','NPR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (154,'Netherlands','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (155,'Netherlands Antilles','Netherlands Antillean Guilder','ANG');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (156,'New Caledonia (French)','CFP Franc','XPF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (157,'New Zealand','New Zealand Dollar','NZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (158,'Nicaragua','Nicaraguan Cordoba Oro','NIO');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (159,'Niger','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (160,'Nigeria','Nigerian Naira','NGN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (161,'Niue','New Zealand Dollar','NZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (162,'Norfolk Island','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (163,'Northern Mariana Islands','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (164,'Norway','Norwegian Krone','NOK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (165,'Oman','Omani Rial','OMR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (166,'Pakistan','Pakistan Rupee','PKR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (167,'Palau','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (168,'Panama','Panamanian Balboa','PAB');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (169,'Papua New Guinea','Papua New Guinea Kina','PGK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (170,'Paraguay','Paraguay Guarani','PYG');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (171,'Peru','Peruvian Nuevo Sol','PEN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (172,'Philippines','Philippine Peso','PHP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (173,'Pitcairn Island','New Zealand Dollar','NZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (174,'Poland','Polish Zloty','PLN');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (175,'Polynesia (French)','CFP Franc','XPF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (176,'Portugal','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (177,'Puerto Rico','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (178,'Qatar','Qatari Rial','QAR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (179,'Reunion (French)','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (180,'Romania','Romanian New Leu','RON');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (181,'Russia','Russian Ruble','RUB');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (182,'Rwanda','Rwanda Franc','RWF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (183,'Saint Helena','St. Helena Pound','SHP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (184,'Saint Kitts & Nevis Anguilla','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (185,'Saint Lucia','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (186,'Saint Pierre and Miquelon','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (187,'Saint Vincent & Grenadines','East Caribbean Dollar','XCD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (188,'Samoa','Samoan Tala','WST');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (189,'San Marino','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (190,'Sao Tome and Principe','Dobra','STD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (191,'Saudi Arabia','Saudi Riyal','SAR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (192,'Senegal','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (193,'Serbia','Dinar','RSD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (194,'Seychelles','Seychelles Rupee','SCR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (195,'Sierra Leone','Sierra Leone Leone','SLL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (196,'Singapore','Singapore Dollar','SGD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (197,'Slovakia','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (198,'Slovenia','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (199,'Solomon Islands','Solomon Islands Dollar','SBD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (200,'Somalia','Somali Shilling','SOS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (201,'South Africa','South African Rand','ZAR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (202,'South Georgia & South Sandwich Islands','Pound Sterling','GBP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (203,'South Sudan','South Sudan Pound','SSP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (204,'Spain','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (205,'Sri Lanka','Sri Lanka Rupee','LKR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (206,'Sudan','Sudanese Pound','SDG');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (207,'Suriname','Surinam Dollar','SRD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (208,'Svalbard and Jan Mayen Islands','Norwegian Krone','NOK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (209,'Swaziland','Swaziland Lilangeni','SZL');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (210,'Sweden','Swedish Krona','SEK');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (211,'Switzerland','Swiss Franc','CHF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (212,'Syria','Syrian Pound','SYP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (213,'Taiwan','Taiwan Dollar','TWD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (214,'Tajikistan','Tajik Somoni','TJS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (215,'Tanzania','Tanzanian Shilling','TZS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (216,'Thailand','Thai Baht','THB');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (217,'Togo','CFA Franc BCEAO','XOF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (218,'Tokelau','New Zealand Dollar','NZD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (219,'Tonga','Tongan Paanga','TOP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (220,'Trinidad and Tobago','Trinidad and Tobago Dollar','TTD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (221,'Tunisia','Tunisian Dollar','TND');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (222,'Turkey','Turkish Lira','TRY');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (223,'Turkmenistan','Manat','TMT');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (224,'Turks and Caicos Islands','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (225,'Tuvalu','Australian Dollar','AUD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (226,'U.K.','Pound Sterling','GBP');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (227,'Uganda','Uganda Shilling','UGX');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (228,'Ukraine','Ukraine Hryvnia','UAH');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (229,'United Arab Emirates','Arab Emirates Dirham','AED');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (230,'Uruguay','Uruguayan Peso','UYU');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (231,'USA','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (232,'USA Minor Outlying Islands','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (233,'Uzbekistan','Uzbekistan Sum','UZS');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (234,'Vanuatu','Vanuatu Vatu','VUV');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (235,'Vatican','Euro','EUR');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (236,'Venezuela','Venezuelan Bolivar','VEF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (237,'Vietnam','Vietnamese Dong','VND');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (238,'Virgin Islands (British)','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (239,'Virgin Islands (USA)','US Dollar','USD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (240,'Wallis and Futuna Islands','CFP Franc','XPF');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (241,'Western Sahara','Moroccan Dirham','MAD');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (242,'Yemen','Yemeni Rial','YER');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (243,'Zambia','Zambian Kwacha','ZMW');
INSERT INTO `currency` (`id`, `country`, `name`, `code`) VALUES (244,'Zimbabwe','Zimbabwe Dollar','ZWD');
