-- country
USE sys_commondb;
TRUNCATE TABLE `country`;
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1605651', 'AS', 'Asia', 'TH', 'Thailand');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1861060', 'AS', 'Asia', 'JP', 'Japan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1814991', 'AS', 'Asia', 'CN', 'China');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2077456', 'OC', 'Oceania', 'AU', 'Australia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1269750', 'AS', 'Asia', 'IN', 'India');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1733045', 'AS', 'Asia', 'MY', 'Malaysia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1835841', 'AS', 'Asia', 'KR', 'South Korea');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1668284', 'AS', 'Asia', 'TW', 'Taiwan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1819730', 'AS', 'Asia', 'HK', 'Hong Kong');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1694008', 'AS', 'Asia', 'PH', 'Philippines');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1562822', 'AS', 'Asia', 'VN', 'Vietnam');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3017382', 'EU', 'Europe', 'FR', 'France');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2921044', 'EU', 'Europe', 'DE', 'Germany');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('294640', 'AS', 'Asia', 'IL', 'Israel');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2661886', 'EU', 'Europe', 'SE', 'Sweden');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3175395', 'EU', 'Europe', 'IT', 'Italy');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('390903', 'EU', 'Europe', 'GR', 'Greece');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2750405', 'EU', 'Europe', 'NL', 'Netherlands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2510769', 'EU', 'Europe', 'ES', 'Spain');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2782113', 'EU', 'Europe', 'AT', 'Austria');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2635167', 'EU', 'Europe', 'GB', 'United Kingdom');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2802361', 'EU', 'Europe', 'BE', 'Belgium');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2658434', 'EU', 'Europe', 'CH', 'Switzerland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('290557', 'AS', 'Asia', 'AE', 'United Arab Emirates');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2017370', 'EU', 'Europe', 'RU', 'Russia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1522867', 'AS', 'Asia', 'KZ', 'Kazakhstan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2623032', 'EU', 'Europe', 'DK', 'Denmark');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2264397', 'EU', 'Europe', 'PT', 'Portugal');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('102358', 'AS', 'Asia', 'SA', 'Saudi Arabia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('130758', 'AS', 'Asia', 'IR', 'Iran');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3144096', 'EU', 'Europe', 'NO', 'Norway');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('6252001', 'NA', 'North America', 'US', 'United States');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3996063', 'NA', 'North America', 'MX', 'Mexico');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('163843', 'AS', 'Asia', 'SY', 'Syria');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('690791', 'EU', 'Europe', 'UA', 'Ukraine');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('146669', 'EU', 'Europe', 'CY', 'Cyprus');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3077311', 'EU', 'Europe', 'CZ', 'Czechia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('99237', 'AS', 'Asia', 'IQ', 'Iraq');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('798549', 'EU', 'Europe', 'RO', 'Romania');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('298795', 'AS', 'Asia', 'TR', 'Turkey');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('272103', 'AS', 'Asia', 'LB', 'Lebanon');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('719819', 'EU', 'Europe', 'HU', 'Hungary');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('614540', 'AS', 'Asia', 'GE', 'Georgia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1149361', 'AS', 'Asia', 'AF', 'Afghanistan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3469034', 'SA', 'South America', 'BR', 'Brazil');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('587116', 'AS', 'Asia', 'AZ', 'Azerbaijan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('6254930', 'AS', 'Asia', 'PS', 'Palestine');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('597427', 'EU', 'Europe', 'LT', 'Lithuania');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('286963', 'AS', 'Asia', 'OM', 'Oman');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('6290252', 'EU', 'Europe', 'RS', 'Serbia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3057568', 'EU', 'Europe', 'SK', 'Slovakia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('660013', 'EU', 'Europe', 'FI', 'Finland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2629691', 'EU', 'Europe', 'IS', 'Iceland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('732800', 'EU', 'Europe', 'BG', 'Bulgaria');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3190538', 'EU', 'Europe', 'SI', 'Slovenia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('617790', 'EU', 'Europe', 'MD', 'Moldova');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('718075', 'EU', 'Europe', 'MK', 'Macedonia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3042058', 'EU', 'Europe', 'LI', 'Liechtenstein');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3042142', 'EU', 'Europe', 'JE', 'Jersey');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('798544', 'EU', 'Europe', 'PL', 'Poland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3202326', 'EU', 'Europe', 'HR', 'Croatia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3277605', 'EU', 'Europe', 'BA', 'Bosnia and Herzegovina');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('453733', 'EU', 'Europe', 'EE', 'Estonia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('458258', 'EU', 'Europe', 'LV', 'Latvia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('248816', 'AS', 'Asia', 'JO', 'Jordan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1527747', 'AS', 'Asia', 'KG', 'Kyrgyzstan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('935317', 'AF', 'Africa', 'RE', 'Réunion');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1024031', 'AF', 'Africa', 'YT', 'Mayotte');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2963597', 'EU', 'Europe', 'IE', 'Ireland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3042225', 'EU', 'Europe', 'IM', 'Isle of Man');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2215636', 'AF', 'Africa', 'LY', 'Libya');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2960313', 'EU', 'Europe', 'LU', 'Luxembourg');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('174982', 'AS', 'Asia', 'AM', 'Armenia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3577718', 'NA', 'North America', 'VG', 'British Virgin Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('69543', 'AS', 'Asia', 'YE', 'Yemen');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('630336', 'EU', 'Europe', 'BY', 'Belarus');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2411586', 'EU', 'Europe', 'GI', 'Gibraltar');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('192950', 'AF', 'Africa', 'KE', 'Kenya');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3895114', 'SA', 'South America', 'CL', 'Chile');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3579143', 'NA', 'North America', 'GP', 'Guadeloupe');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3570311', 'NA', 'North America', 'MQ', 'Martinique');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3381670', 'SA', 'South America', 'GF', 'French Guiana');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('241170', 'AF', 'Africa', 'SC', 'Seychelles');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3624060', 'NA', 'North America', 'CR', 'Costa Rica');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3508796', 'NA', 'North America', 'DO', 'Dominican Republic');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('6251999', 'NA', 'North America', 'CA', 'Canada');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4566966', 'NA', 'North America', 'PR', 'Puerto Rico');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4796775', 'NA', 'North America', 'VI', 'U.S. Virgin Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2186224', 'OC', 'Oceania', 'NZ', 'New Zealand');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1880251', 'AS', 'Asia', 'SG', 'Singapore');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1643084', 'AS', 'Asia', 'ID', 'Indonesia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1282988', 'AS', 'Asia', 'NP', 'Nepal');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2088628', 'OC', 'Oceania', 'PG', 'Papua New Guinea');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1168579', 'AS', 'Asia', 'PK', 'Pakistan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3703430', 'NA', 'North America', 'PA', 'Panama');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3374084', 'NA', 'North America', 'BB', 'Barbados');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3572887', 'NA', 'North America', 'BS', 'Bahamas');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3576468', 'NA', 'North America', 'LC', 'Saint Lucia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3865483', 'SA', 'South America', 'AR', 'Argentina');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1210997', 'AS', 'Asia', 'BD', 'Bangladesh');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4031074', 'OC', 'Oceania', 'TK', 'Tokelau');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1821275', 'AS', 'Asia', 'MO', 'Macao');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1831722', 'AS', 'Asia', 'KH', 'Cambodia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1282028', 'AS', 'Asia', 'MV', 'Maldives');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2139685', 'OC', 'Oceania', 'NC', 'New Caledonia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2205218', 'OC', 'Oceania', 'FJ', 'Fiji');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2029969', 'AS', 'Asia', 'MN', 'Mongolia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4034749', 'OC', 'Oceania', 'WF', 'Wallis and Futuna');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('289688', 'AS', 'Asia', 'QA', 'Qatar');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('783754', 'EU', 'Europe', 'AL', 'Albania');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1512440', 'AS', 'Asia', 'UZ', 'Uzbekistan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('285570', 'AS', 'Asia', 'KW', 'Kuwait');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3194884', 'EU', 'Europe', 'ME', 'Montenegro');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3582678', 'NA', 'North America', 'BZ', 'Belize');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1873107', 'AS', 'Asia', 'KP', 'North Korea');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3164670', 'EU', 'Europe', 'VA', 'Vatican City');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('6697173', 'AN', 'Antarctica', 'AQ', 'Antarctica');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3932488', 'SA', 'South America', 'PE', 'Peru');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3573345', 'NA', 'North America', 'BM', 'Bermuda');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('7626836', 'NA', 'North America', 'CW', 'Curaçao');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3686110', 'SA', 'South America', 'CO', 'Colombia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3625428', 'SA', 'South America', 'VE', 'Venezuela');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3658394', 'SA', 'South America', 'EC', 'Ecuador');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('953987', 'AF', 'Africa', 'ZA', 'South Africa');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3923057', 'SA', 'South America', 'BO', 'Bolivia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3042362', 'EU', 'Europe', 'GG', 'Guernsey');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2562770', 'EU', 'Europe', 'MT', 'Malta');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1220409', 'AS', 'Asia', 'TJ', 'Tajikistan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('290291', 'AS', 'Asia', 'BH', 'Bahrain');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2328926', 'AF', 'Africa', 'NG', 'Nigeria');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('357994', 'AF', 'Africa', 'EG', 'Egypt');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('878675', 'AF', 'Africa', 'ZW', 'Zimbabwe');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2275384', 'AF', 'Africa', 'LR', 'Liberia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2300660', 'AF', 'Africa', 'GH', 'Ghana');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('149590', 'AF', 'Africa', 'TZ', 'Tanzania');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('895949', 'AF', 'Africa', 'ZM', 'Zambia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3355338', 'AF', 'Africa', 'NA', 'Namibia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1062947', 'AF', 'Africa', 'MG', 'Madagascar');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3351879', 'AF', 'Africa', 'AO', 'Angola');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2287781', 'AF', 'Africa', 'CI', 'Ivory Coast');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('366755', 'AF', 'Africa', 'SD', 'Sudan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('226074', 'AF', 'Africa', 'UG', 'Uganda');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2233387', 'AF', 'Africa', 'CM', 'Cameroon');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('927384', 'AF', 'Africa', 'MW', 'Malawi');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2400553', 'AF', 'Africa', 'GA', 'Gabon');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2453866', 'AF', 'Africa', 'ML', 'Mali');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2395170', 'AF', 'Africa', 'BJ', 'Benin');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2434508', 'AF', 'Africa', 'TD', 'Chad');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('933860', 'AF', 'Africa', 'BW', 'Botswana');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3374766', 'AF', 'Africa', 'CV', 'Cape Verde');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('49518', 'AF', 'Africa', 'RW', 'Rwanda');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2260494', 'AF', 'Africa', 'CG', 'Republic of the Congo');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1036973', 'AF', 'Africa', 'MZ', 'Mozambique');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2413451', 'AF', 'Africa', 'GM', 'Gambia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('932692', 'AF', 'Africa', 'LS', 'Lesotho');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('934292', 'AF', 'Africa', 'MU', 'Mauritius');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2542007', 'AF', 'Africa', 'MA', 'Morocco');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2589581', 'AF', 'Africa', 'DZ', 'Algeria');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2420477', 'AF', 'Africa', 'GN', 'Guinea');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('203312', 'AF', 'Africa', 'CD', 'Congo');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('934841', 'AF', 'Africa', 'SZ', 'Swaziland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2361809', 'AF', 'Africa', 'BF', 'Burkina Faso');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2403846', 'AF', 'Africa', 'SL', 'Sierra Leone');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('51537', 'AF', 'Africa', 'SO', 'Somalia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2440476', 'AF', 'Africa', 'NE', 'Niger');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('239880', 'AF', 'Africa', 'CF', 'Central African Republic');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2363686', 'AF', 'Africa', 'TG', 'Togo');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('433561', 'AF', 'Africa', 'BI', 'Burundi');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2309096', 'AF', 'Africa', 'GQ', 'Equatorial Guinea');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('7909807', 'AF', 'Africa', 'SS', 'South Sudan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2245662', 'AF', 'Africa', 'SN', 'Senegal');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2378080', 'AF', 'Africa', 'MR', 'Mauritania');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('223816', 'AF', 'Africa', 'DJ', 'Djibouti');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('921929', 'AF', 'Africa', 'KM', 'Comoros');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2464461', 'AF', 'Africa', 'TN', 'Tunisia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3425505', 'NA', 'North America', 'GL', 'Greenland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('831053', 'EU', 'Europe', 'XK', 'Kosovo');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3580718', 'NA', 'North America', 'KY', 'Cayman Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3489940', 'NA', 'North America', 'JM', 'Jamaica');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3595528', 'NA', 'North America', 'GT', 'Guatemala');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2080185', 'OC', 'Oceania', 'MH', 'Marshall Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3577279', 'NA', 'North America', 'AW', 'Aruba');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2993457', 'EU', 'Europe', 'MC', 'Monaco');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3573511', 'NA', 'North America', 'AI', 'Anguilla');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3575174', 'NA', 'North America', 'KN', 'Saint Kitts and Nevis');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3580239', 'NA', 'North America', 'GD', 'Grenada');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3437598', 'SA', 'South America', 'PY', 'Paraguay');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3578097', 'NA', 'North America', 'MS', 'Montserrat');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3576916', 'NA', 'North America', 'TC', 'Turks and Caicos Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3576396', 'NA', 'North America', 'AG', 'Antigua and Barbuda');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2110297', 'OC', 'Oceania', 'TV', 'Tuvalu');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4030656', 'OC', 'Oceania', 'PF', 'French Polynesia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2103350', 'OC', 'Oceania', 'SB', 'Solomon Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2134431', 'OC', 'Oceania', 'VU', 'Vanuatu');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('338010', 'AF', 'Africa', 'ER', 'Eritrea');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3573591', 'NA', 'North America', 'TT', 'Trinidad and Tobago');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3041565', 'EU', 'Europe', 'AD', 'Andorra');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3370751', 'AF', 'Africa', 'SH', 'Saint Helena');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3585968', 'NA', 'North America', 'SV', 'El Salvador');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3608932', 'NA', 'North America', 'HN', 'Honduras');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3439705', 'SA', 'South America', 'UY', 'Uruguay');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1227603', 'AS', 'Asia', 'LK', 'Sri Lanka');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2078138', 'AS', 'Asia', 'CX', 'Christmas Island');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1282588', 'AS', 'Asia', 'IO', 'British Indian Ocean Territory');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4034894', 'OC', 'Oceania', 'WS', 'Samoa');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3382998', 'SA', 'South America', 'SR', 'Suriname');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1899402', 'OC', 'Oceania', 'CK', 'Cook Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4030945', 'OC', 'Oceania', 'KI', 'Kiribati');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4036232', 'OC', 'Oceania', 'NU', 'Niue');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4032283', 'OC', 'Oceania', 'TO', 'Tonga');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1546748', 'AN', 'Antarctica', 'TF', 'French Southern Territories');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2155115', 'OC', 'Oceania', 'NF', 'Norfolk Island');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1820814', 'AS', 'Asia', 'BN', 'Brunei');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1218197', 'AS', 'Asia', 'TM', 'Turkmenistan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4030699', 'OC', 'Oceania', 'PN', 'Pitcairn Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3168068', 'EU', 'Europe', 'SM', 'San Marino');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('661882', 'EU', 'Europe', 'AX', 'Åland');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2622320', 'EU', 'Europe', 'FO', 'Faroe Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('607072', 'EU', 'Europe', 'SJ', 'Svalbard and Jan Mayen');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1547376', 'AS', 'Asia', 'CC', 'Cocos [Keeling] Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2110425', 'OC', 'Oceania', 'NR', 'Nauru');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('5854968', 'OC', 'Oceania', 'UM', 'U.S. Minor Outlying Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('7609695', 'NA', 'North America', 'SX', 'Sint Maarten');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2372248', 'AF', 'Africa', 'GW', 'Guinea-Bissau');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1559582', 'OC', 'Oceania', 'PW', 'Palau');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('5880801', 'OC', 'Oceania', 'AS', 'American Samoa');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1252634', 'AS', 'Asia', 'BT', 'Bhutan');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3578421', 'NA', 'North America', 'MF', 'Saint Martin');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3577815', 'NA', 'North America', 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3424932', 'NA', 'North America', 'PM', 'Saint Pierre and Miquelon');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3578476', 'NA', 'North America', 'BL', 'Saint Barthélemy');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3575830', 'NA', 'North America', 'DM', 'Dominica');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2410758', 'AF', 'Africa', 'ST', 'São Tomé and Príncipe');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3474414', 'SA', 'South America', 'FK', 'Falkland Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4041468', 'OC', 'Oceania', 'MP', 'Northern Mariana Islands');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1966436', 'OC', 'Oceania', 'TL', 'East Timor');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('7626844', 'NA', 'North America', 'BQ', 'Bonaire');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('4043988', 'OC', 'Oceania', 'GU', 'Guam');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('2081918', 'OC', 'Oceania', 'FM', 'Micronesia');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3378535', 'SA', 'South America', 'GY', 'Guyana');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3617476', 'NA', 'North America', 'NI', 'Nicaragua');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1327865', 'AS', 'Asia', 'MM', 'Myanmar [Burma]');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3723988', 'NA', 'North America', 'HT', 'Haiti');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('1655842', 'AS', 'Asia', 'LA', 'Laos');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('3562981', 'NA', 'North America', 'CU', 'Cuba');
INSERT INTO `country` (`geoname_id`, `continent_code`, `continent_name`, `country_iso_code`, `country_name`) VALUES ('337996', 'AF', 'Africa', 'ET', 'Ethiopia');