-- state
TRUNCATE TABLE `state`;
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'V', 'TIERRA DEL FUEGO');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'L', 'LA PAMPA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'A', 'SALTA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'R', 'RIO NEGRO');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'G', 'SANTIAGO DEL ESTERO');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'W', 'CORRIENTES');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'M', 'MENDOZA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'B', 'BUENOS AIRES');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'S', 'SANTA FE');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'H', 'CHACO');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'X', 'CORDOBA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'N', 'MISIONES');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'D', 'SAN LUIS');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'T', 'TUCUMAN');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'J', 'SAN JUAN');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'Y', 'JUJUY');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'P', 'FORMOSA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'E', 'ENTRE RIOS');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'U', 'CHUBUT');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'K', 'CATAMARCA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'Z', 'SANTA CRUZ');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'Q', 'NEUQUEN');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AR', 'F', 'LA RIOJA');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AS', '60', 'As');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AT', '5', 'Salzburg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AT', '1', 'Burgenland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AT', '6', 'Steiermark');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AT', '2', 'Kaernten');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AT', '7', 'Tirol');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AT', '8', 'Vorarlberg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'SA', 'South Australia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'ACT', 'Australian Capital Territory');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'TAS', 'Tasmania');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'NSW', 'New South Wales');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'VIC', 'Victoria');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'NT', 'Northern Territory');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'WA', 'Western Australia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('AU', 'QLD', 'Queensland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BE', 'BRU', 'Bruxelles-Capitale');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BE', 'VLG', 'Vlaanderen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BE', 'WAL', 'Wallonie');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '23', 'Rio Grande do Sul');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '13', 'Maranhao');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '28', 'Sergipe');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '18', 'Parana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '24', 'Rondonia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '14', 'Mato Grosso');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '29', 'Goias');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '20', 'Piaui');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '25', 'Roraima');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '15', 'Minas Gerais');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '30', 'Pernambuco');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '21', 'Rio de Janeiro');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '26', 'Santa Catarina');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '16', 'Para');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '31', 'Tocantins');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '22', 'Rio Grande do Norte');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '11', 'Mato Grosso do Sul');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '27', 'Sao Paulo');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('BR', '17', 'Paraiba');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'AB', 'Alberta');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'NS', 'Nova Scotia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'SK', 'Saskatchewan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'BC', 'British Columbia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'NU', 'Nunavut Territory');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'YT', 'Yukon');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'MB', 'Manitoba');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'ON', 'Ontario');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'NB', 'New Brunswick');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'PE', 'Prince Edward Island');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'NL', 'Newfoundland and Labrador');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CA', 'QC', 'Quebec');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'TI', 'Cantone Ticino');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'LU', 'Kanton Luzern');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'AR', 'Kanton Appenzell Ausserrhoden');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'SH', 'Kanton Schaffhausen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'UR', 'Kanton Uri');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'BE', 'Kanton Bern');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'SO', 'Kanton Solothurn');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'GL', 'Kanton Glarus');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'VD', 'Canton de Vaud');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'NW', 'Kanton Nidwalden');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'BL', 'Kanton Basel-Landschaft');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'SZ', 'Kanton Schwyz');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'AG', 'Kanton Aargau');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'VS', 'Canton du Valais');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'OW', 'Kanton Obwalden');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'BS', 'Kanton Basel-Stadt');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'TG', 'Kanton Thurgau');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'JU', 'Canton du Jura');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'AI', 'Kanton Appenzell Innerrhoden');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'ZG', 'Kanton Zug');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'SG', 'Kanton St. Gallen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('CH', 'FR', 'Canton de Fribourg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'RP', 'Rheinland-Pfalz');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'HE', 'Hessen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'SL', 'Saarland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'BB', 'Brandenburg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'HH', 'Hamburg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'SN', 'Sachsen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'MV', 'Mecklenburg-Vorpommern');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'ST', 'Sachsen-Anhalt');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'BY', 'Bayern');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'NI', 'Niedersachsen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DE', 'HB', 'Bremen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DK', '1081', 'Region Nordjylland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DK', '1082', 'Region Midtjylland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DK', '1083', 'Region Syddanmark');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DK', '1084', 'Region Hovedstaden');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '42', 'Tipaza');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '47', 'Ghardaia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '33', 'Illizi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '38', 'Tissemsilt');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '43', 'Mila');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '10', 'Bouira');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '48', 'Relizane');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '34', 'Bordj-Bou-Arreridj');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '39', 'El-Oued');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '44', 'Ain-Defla');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '12', 'Tebessa');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '35', 'Boumerdes');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '40', 'Khenchela');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '45', 'Naama');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '19', 'Setif');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '36', 'El-Taref');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '41', 'Souk-Ahras');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '46', 'Ain-Temouchent');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '32', 'El-Bayadh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('DZ', '37', 'Tindouf');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'RI', 'La Rioja');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'CT', 'Cataluna');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'MD', 'Madrid');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'CE', 'Ceuta');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'VC', 'Comunidad Valenciana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'EX', 'Extremadura');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'ML', 'Melilla');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'CL', 'Castilla - Leon');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'GA', 'Galicia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'AN', 'Andalucia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'NC', 'Navarra');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'CM', 'Castilla - La Mancha');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'IB', 'Baleares');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'AS', 'Asturias');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'PV', 'Pais Vasco');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'CN', 'Canarias');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'MC', 'Murcia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('ES', 'CB', 'Cantabria');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A5', 'Corse');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'C1', 'Alsace');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'B1', 'Limousin');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A1', 'Bourgogne');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'B6', 'Picardie');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'B2', 'Lorraine');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A2', 'Bretagne');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'B7', 'Poitou-Charentes');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A7', 'Haute-Normandie');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', '97', 'Aquitaine');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A3', 'Centre');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', '98', 'Auvergne');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'B4', 'Nord-Pas-de-Calais');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A4', 'Champagne-Ardenne');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'A9', 'Languedoc-Roussillon');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', '99', 'Basse-Normandie');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('FR', 'B5', 'Pays de la Loire');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GB', 'ENG', 'England');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GB', 'NIR', 'Northern Ireland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GB', 'SCT', 'Scotland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GB', 'WLS', 'Wales');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GF', 'GF', 'Guyane');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GP', 'GP', 'Guadeloupe');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GU', '66', 'Gu');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('GU', 'GU', 'Guam');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('HU', 'BA', 'Baranya');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('HU', 'TO', 'Tolna');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('HU', 'VA', 'Vas');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('HU', 'BU', 'Budapest');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('HU', 'ZA', 'Zala');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'OR', 'Orisa');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'JH', 'Jharkhand');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'AP', 'Andhra Pradesh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'TR', 'Tripura');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'MM', 'Maharashtra');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'DN', 'Dadar and Nagar Haveli');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'PB', 'Punjab');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'JK', 'Jammu and Kashmir');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'BR', 'Bihar');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'UL', 'Uttaranchal');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'MN', 'Manipur');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'GJ', 'Gujarat');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'PY', 'Pondicherry');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'KA', 'Karnataka');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'CH', 'Chandigarh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'UP', 'Uttar Pradesh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'MP', 'Madhya Pradesh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'HP', 'Himachal Pradesh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'RJ', 'Rajasthan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'KL', 'Kerala');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'DD', 'Daman and Diu');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'WB', 'West Bengal');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'MZ', 'Mizoram');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'HR', 'Haryana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'TN', 'Tamil Nadu');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'LD', 'Lakshadweep');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IN', 'DL', 'New Delhi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'CI', 'Calabria');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'VN', 'Veneto');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'LZ', 'Lazio');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'SD', 'Sardegna');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'ER', 'Emilia-Romagna');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'MH', 'Marche');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'TC', 'Toscana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'FV', 'Friuli-Venezia Giulia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'PM', 'Piemonte');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'TT', 'Trentino-Alto Adige');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'LG', 'Liguria');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'PU', 'Puglia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'UM', 'Umbria');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'LM', 'Lombardia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('IT', 'SC', 'Sicilia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7009', 'Gamprin');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7005', 'Schaan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7010', 'Ruggell');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7001', 'Vaduz');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7006', 'Planken');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7011', 'Schellenberg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7002', 'Triesen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7007', 'Eschen');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7003', 'Balzers');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7008', 'Mauren');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('LI', '7004', 'Triesenberg');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MH', '68', 'Mh');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MP', '69', 'Mp');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MQ', 'MQ', 'Martinique');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'CAM', 'Campeche');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'NAY', 'Nayarit');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'TAB', 'Tabasco');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'DIF', 'Distrito Federal');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'ROO', 'Quintana Roo');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'ZAC', 'Zacatecas');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'JAL', 'Jalisco');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'CHH', 'Colima');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'NLE', 'Nuevo Leon');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'TAM', 'Tamaulipas');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'DUR', 'Durango');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'AGU', 'Aguascalientes');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'SIN', 'Sinaloa');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'MEX', 'Mexico');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'CHP', 'Coahuila De Zaragoza');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'OAX', 'Oaxaca');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'TLA', 'Tlaxcala');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'GRO', 'Guerrero');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'BCN', 'Baja California');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'MIC', 'Michoacan De Ocampo');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'SLP', 'San Luis Potosi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'COA', 'Chiapas');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'PUE', 'Puebla');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'VER', 'Veracruz Llave');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'GUA', 'Guanajuato');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'BCS', 'Baja California Sur');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'MOR', 'Morelos');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'SON', 'Sonora');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'COL', 'Chihuahua');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'QUE', 'Queretaro De Arteaga');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'YUC', 'Yucatan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MX', 'HID', 'Hidalgo');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'SBH', 'Sabah');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'KUL', 'Kuala Lumpur');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'PJY', 'Putrajaya');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'SGR', 'Selangor');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'LBN', 'Labuan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'PLS', 'Perlis');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'JHR', 'Johor');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'SRW', 'Sarawak');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'MLK', 'Melaka');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'PNG', 'Pulau Pinang');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'KDH', 'Kedah');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'TRG', 'Terengganu');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'NSN', 'Negeri Sembilan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'PRK', 'Perak');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'KTN', 'Kelantan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('MY', 'PHG', 'Pahang');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('PM', '97502', 'Saint-Pierre');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('PM', '97501', 'Miquelon-Langlade');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('PR', '72', 'Pr');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('PR', 'PR', 'Puerto Rico');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('PT', '49', 'Ilha do Corvo');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('RE', '0', 'Reunion (general)');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('SE', 'I', 'Gotland');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('SE', 'BD', 'Norrbotten');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('SE', 'C', 'Uppsala');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '65', 'Phitsanulok');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '54', 'Phrae');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '92', 'Trang');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '76', 'Phetchabun');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '61', 'Uthai Thani');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '50', 'Chiang Mai');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '84', 'Surat Thani');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '70', 'Ratchaburi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '55', 'Nan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '94', 'Pattani');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '78', 'Phetchaburi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '62', 'Kamphaeng Phet');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '51', 'Lamphun');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '85', 'Ranong');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '73', 'Nakhon Pathom');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '56', 'Phayao');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '95', 'Yala');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '81', 'Krabi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '63', 'Tak');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '52', 'Lampang');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '90', 'Songkhla');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '74', 'Samut Sakhon');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '57', 'Chiang Rai');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '96', 'Narathiwat');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '82', 'Phang Nga');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '64', 'Sukhothai');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '53', 'Uttaradit');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '91', 'Satun');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '75', 'Samut Songkhram');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '58', 'Mae Hong Son');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TH', '83', 'Phuket');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '9', 'Aydin');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '77', 'Yalova');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '2', 'Adiyaman');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '6', 'Ankara');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '79', 'Kilis');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '3', 'Afyonkarahisar');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '67', 'Zonguldak');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '8', 'Artvin');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '7', 'Antalya');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '80', 'Osmaniye');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '5', 'Amasya');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '71', 'Kirikkale');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('TR', '1', 'Adana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'OK', 'Oklahoma');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'MS', 'Mississippi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'IL', 'Illinois');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'VT', 'Vermont');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'CA', 'California');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'NM', 'New Mexico');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'MA', 'Massachusetts');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'PA', 'Pennsylvania');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'MT', 'Montana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'IN', 'Indiana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'WI', 'Wisconsin');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'CO', 'Colorado');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'NV', 'Nevada');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'ME', 'Maine');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'HI', 'Hawaii');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'AK', 'Alaska');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'ND', 'North Dakota');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'KS', 'Kansas');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'WV', 'West Virginia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'DC', 'District of Columbia');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'NY', 'New York');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'MI', 'Michigan');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'IA', 'Iowa');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'TX', 'Texas');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'AL', 'Alabama');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'NH', 'New Hampshire');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'KY', 'Kentucky');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'WY', 'Wyoming');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'DE', 'Delaware');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'OH', 'Ohio');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'MO', 'Missouri');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'ID', 'Idaho');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'UT', 'Utah');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'AZ', 'Arizona');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'NJ', 'New Jersey');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'LA', 'Louisiana');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('US', 'FL', 'Florida');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97607', 'Dembeni');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97613', 'MTsangamouji');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97603', 'Bandrele');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97614', 'Ouangani');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97610', 'Koungou');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97616', 'Sada');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97605', 'Chiconi');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97611', 'Mamoudzou');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97617', 'Tsingoni');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97606', 'Chirongui');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97612', 'Mtsamboro');
INSERT INTO `state` (`country_iso_code`, `state_code`, `state_name`) VALUES ('YT', '97602', 'Bandraboua');